# Generated by Django 3.2.19 on 2023-07-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_pet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
        migrations.DeleteModel(
            name='Raca',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
