# Generated by Django 3.2.19 on 2023-07-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('p', 'Para adocao'), ('A', 'Adotado')], default='P', max_length=1),
        ),
    ]
