# Generated by Django 3.2.19 on 2023-07-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_alter_pet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('P', 'Para adocao'), ('A', 'Adotado')], default='P', max_length=1),
        ),
    ]
